### ISSUE TITLE
Investigate how a user can get single predictions on timeseries models

### ISSUE THREAD

**Issue by tomhuds** [mindsdb/lightwood#1052]
Possible approaches
- Use a similar logic to LATEST, where mindsdb fetches the necessary rows to fill the window
- The above, but with an alternative syntax e.g. PREDICT .... GIVEN
- Educate users that they need to select > window rows

Additional questions
- If window is not full for a row, should any predictions be returned?

**Comment by tomhuds** [comment]
One idea:
- **WHERE order_by_col_name = t** corresponds to 'give me predictions as if I was at time = t'
- MindsDB fills the necessary inputs for that row
- If you want predictions into the future, you could use **WHERE order_by_col_name = LATEST**
- If you want predictions for your current time, you could use **WHERE order_by_col_name = LATEST-1**
- If there aren't enough rows for a full window (let's say you ask for predictions at the first row in the the table), we could either:
a) Not return anything (ok)
b) Have a flag for 'incomplete_window' (better)

**Comment by paxcema** [comment]
> WHERE order_by_col_name = t corresponds to 'give me predictions as if I was at time = t'

This can be triggered with bulk prediction mode (and no `LATEST`). I've got to double check there is no offset error for this mode (i.e. we're not predicting at t-1 or t+1).

_However_, lightwood does not impute the starting rows with missing context. This is fine, as you said, it should be MindsDB's job to do that (and right now it's not being done).

> If you want predictions into the future, you could use WHERE order_by_col_name = LATEST.

95% sure this is working right now, will double check. Again, there may be an off-by-one situation that I have to check (it's tracked in #1047)

> If you want predictions for your current time, you could use WHERE order_by_col_name = LATEST-1

This is supported by lightwood right now, but MindsDB (the LW handler) doesn't expose it yet AFAIK.

> If there aren't enough rows for a full window (let's say you ask for predictions at the first row in the the table), we could either:
a) Not return anything (ok)
b) Have a flag for 'incomplete_window' (better)

Lightwood does pretty much exactly b) as you're outlining it :) We log a warning _if_ `TimeseriesSettings.allow_incomplete_history` is set to True. Otherwise, an exception is raised.

**Comment by paxcema** [comment]
For more context into the OP question, there is also [this reply](https://github.com/mindsdb/lightwood/issues/1055#issuecomment-1332686744) in #1055.

**Comment by paxcema** [comment]
Closing, all related bugs have issues of their own and the question here has been answered.
