### ISSUE TITLE
Add multiple categories data type

### ISSUE THREAD

**Issue by btseytlin** [mindsdb/lightwood#203]
Basically add ability to do multi-label classification.

Example dataset for multi-label classification: https://www.kaggle.com/cryptexcode/mpst-movie-plot-synopses-with-tags

**Comment by maximlopin** [comment]
I think in lightwood this can be thought of as a normal classification problem and we don't need a new data type, am I missing something?
example:

```
tags
horror,romantic,mystery
romantic,mystery
mystery
horror,mystery

```
becomes this:
```
horror romantic mystery
1         1             1
0         1             1
0         0             1
1         0             1
```

In mindsdb_native it does make sense to have a new datatype (mindsdb_native/issues/63), because we don't want to alter the columns there.

**Comment by maximlopin** [comment]
I think I just realized that I'm wrong here, because that's exactly why we need a new data type in lightwood, a special case when we have a column with, say comma-separated categories, and we want to output prediction for the initial column "tags" rather than predictions for separate tags(categories).

**Comment by btseytlin** [comment]
@maximlopin you are correct, this multi-hot representation is what I am going with. However it does need to be a different data type because it needs to use a different encoder and a slightly different loss

**Comment by George3d6** [comment]
I believe this has been added to lightwood, just need to add it to mindsdb_native now
