### ISSUE TITLE
RuntimeError in categorical autoencoder, shape mismatch during ModelInterface

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#237]
**Your Environment**

* Python version: 3.6.11
* Operating system: Ubuntu 16.04
* Lightwood version: 0.33.0
* MindsDB Native version: 2.1.1

**Please describe your issue and how we can replicate it**

Using the `mindsdb_traffic` dataset, the categorical autoencoder fails with a tensor shape mismatch when multiplying. Stack trace is [here](https://github.com/mindsdb/lightwood/files/5024886/log.txt).

**Comment by paxcema** [comment]
Also happening during the ModelAnalyzer phase, when using [this](https://www.kaggle.com/nicapotato/womens-ecommerce-clothing-reviews) dataset. To replicate:

```
import mindsdb
import pandas as pd

df = pd.read_csv("Womens Clothing Subset.csv")
pred = mindsdb.Predictor(name='test')
pred.learn(from_data=df, to_predict='Class Name')
```

Stack trace is [here](https://github.com/mindsdb/lightwood/files/5092432/log.txt).

**Comment by George3d6** [comment]
Downloaded and unziped the data from the link, tried to replicate via:

```
import mindsdb_native
import pandas as pd

df = pd.read_csv("Womens Clothing E-Commerce Reviews.csv")
pred = mindsdb_native.Predictor(name='test')
pred.learn(from_data=df, to_predict='Class Name', ignore_columns=['Review Text'])
```

Ignoring "Review Text" since it was being classified as text and encoded using BERT which made the whole thing even longer.

Can't replicate so will be closing this until replication is possible. No idea what could have been causing this bug, but it's a long time ago.
