### ISSUE TITLE
pretrained_lang encoder should call 'uses_target' and 'is_nn_encoder' as a keyword arguments

### ISSUE THREAD

**Issue by hakunanatasha** [mindsdb/lightwood#491]
J{ai}son will check whether uses_target flag exists in the encoder -if so, it enables you to feed in encoded data target while training. 

We should make these passable defaults as opposed to setting these attributes into the encoder.

this currently only affects pretrained_lang

**Comment by George3d6** [comment]
passable defaults == argument in constructor with default values

**Comment by George3d6** [comment]
We need a few default flags to tell us how an encoder is prepared:
* uses GPU

**Comment by George3d6** [comment]
* Make prepare optional, so that encoders which don't need to be prepared, can be left alone, making their implementation simpler
* `dependencies` becomes a dictionary (instead of a list) and it contains the column name (as the key) and a boolean indicating if the data should be encoded or decoded as the value.

**Comment by George3d6** [comment]
We can check for these in the base encoder.
