### ISSUE TITLE
'Unknown' value in data analysis histogram

### ISSUE THREAD

**Issue by StpMax** [mindsdb/lightwood#564]
Upload [this csv](https://www.kaggle.com/ruchi798/malnutrition-across-the-globe?select=country-wise-average.csv) as datasource and click on analysis. In results will be:
```
analysis['statistical_analysis]['histograms']['Country] = {'x': ['Unknown'], 'y': [152]}
```
 But shouldn't there be `{'x': ['AFGHANISTAN', 'ALBANIA', ...], 'y': [1,1,1,1...]}` instead?

**Comment by George3d6** [comment]
`Country` is detected as an identifier. since each country is unique. and not being text or numerical this means it holds no information. Working as intended, but it might be a bit confusing that we even have histograms for identifier (?)

If you require further changes for mindsdb to communicate to the user which columns are not being used and why do make a separate issue (but I guess not the case right now based on the chat in slack?)
