### ISSUE TITLE
CSV with the dataset from the deernet paper

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#673]
I loved this paper: https://arxiv.org/pdf/2106.07465.pdf and I'd love to add the dataset they are using to our benchmark.

However, I'm unsure how to use the physics library required to generate the data and would rather just have a simple CSV with the data (csv columns can contain arrays if need be, but I don't think this will be required here).

Feel free to PR this csv into https://github.com/mindsdb/benchmarks

This will count 3 points towards the hacktoberfest deep learning laptop raffle.

**Comment by MichaelLantz** [comment]
I have two separate pull requests due to the differing methods used to generate results based on the two sets of libraries / examples (Spinach[https://spindynamics.org/documents/spinach_2_6_5625.zip] and [DeerAnalysis](https://ethz.ch/content/dam/ethz/special-interest/chab/physical-chemistry/epr-dam/documents/software/deer-15-on/DeerAnalysis2021b.zip))

**Comment by George3d6** [comment]
seems almost done, cheers :D

**Comment by MichaelLantz** [comment]
To quote the great McConaughey “all right, all right, all right” 🥇.  I just hope it's a helpful benchmark and my google-fu helped provide a quality product. Apologies for including and additional .zip in each change-set that deviated slightly from other examples. Considering this was my first venture into the benchmark project I figured it would be helpful for a reviewer to have all the tools / data (minus Matlab and physics libraries) to make sense of how I got to the final CSV's.  Cheers!
